config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  root :to => "users#index"

  resources :users, only: [:index, :new, :show, :create] do
    get 'gifts', on: :member
    get 'delete', on: :member
    patch 'avatar', on: :member
    get 'bann', on: :member
  end

  
  
  resources :gifts, only: [:index, :new, :show, :create, :update]

end

app/models/gift.rb
class Gift < ActiveRecord::Base

  has_many :user_gifts
  has_many :users, through: :user_gifts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  has_many :user_gifts
  has_many :gifts, through: :user_gifts

end

app/models/user_gift.rb
class UserGift < ActiveRecord::Base

  belongs_to :user
  belongs_to :gift

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :check_role
  before_action :check_status
  # before_action :check_role

  # def check_role
  #   redirent_to root_url unless current_user.admin?
  # end

  # def current_user
  #   # find current user
  # end

  private

  def check_role
    unless !current_user.nil? && current_user.role.nil?
      return true
    end
  end

  def check_status
    if current_user && current_user.status == "banned"

      redirect_to root_path
    end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]
  #skip_before_action :check_status, only:


  # GET /gifts
  # GET /gifts.json
  def index

    @gifts = Gift.all

    #binding.pry

  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to gifts_url, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new , notice: 'Bad user id or problems with saving'}
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update

    respond_to do |format|

      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit, notice: 'Bad user id or problems with saving' }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white index through.
    def gift_params
      params.require(:gift).permit(:name, :visible, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Override the action you want here.
  skip_before_action :check_status

  def create
    super

    UserMailer.welcome_email(params[:user]).deliver_now
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  skip_before_action :check_status, only: :destroy

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
     super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # NEED to avoid dead loop
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :check_role, only: :index
  skip_before_action :check_status, only: :index
  # before_action , only:

  def index
    @users_list = User.all

    #user = {:email => "dmitriy.smus@gmail.com" }

    #mail = UserMailer.welcome_email(user)

    puts params

    @users_list = User.paginate(:page => params[:page], :per_page => 2)
    @q = @users_list.ransack(params[:q])
    #@users_list = @q.result()

    #binding.pry

  end

  def avatar

    user = User.find(params[:id])

    user.update(user_params)

    redirect_to root_path
  end

  def bann

    user = User.find(params[:id])

    if !user.role
      user.update_attribute(:status, :banned)
    end

    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  # NEED WRITE
  def gifts

  end

  def delete

    @users_list = User.all.order(:id)

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/user_gifts_helper.rb
module UserGiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
    <% if @gift.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

          <ul>
            <% @gift.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :visible %><br>
      <%= f.text_field :visible %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gifts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Visible</th>
      <th>Details</th>
      <th>Edit This gift</th>
      <th>Destroy this gift</th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.name %></td>
        <td><%= gift.visible %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', '#' %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>New Gift</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gift.name %>
</p>

<%= link_to 'Back', gifts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Gifts", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Gifts", gifts_path %></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
          <% else %>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/user_gifts/_form.html.erb
<%= form_for(@user_gift) do |f| %>
  <% if @user_gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_gift.errors.count, "error") %> prohibited this user_gift from being saved:</h2>

      <ul>
      <% @user_gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :gift_id %><br>
    <%= f.number_field :gift_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_gifts/edit.html.erb
<h1>Editing User Gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_gift %> |
<%= link_to 'Back', user_gifts_path %>

app/views/user_gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Gifts</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Gift</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_gifts.each do |user_gift| %>
      <tr>
        <td><%= user_gift.id %></td>
        <td><%= user_gift.name %></td>
        <td><%= link_to 'Show', user_gift %></td>
        <td><%= link_to 'Destroy', user_gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User gift', new_user_gift_path %>

app/views/user_gifts/new.html.erb
<h1>New User Gift</h1>

<%= render 'form' %>

<%= link_to 'Back', user_gifts_path %>

app/views/user_gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_gift.user_id %>
</p>

<p>
  <strong>Gift:</strong>
  <%= @user_gift.gift_id %>
</p>

<%= link_to 'Edit', edit_user_gift_path(@user_gift) %> |
<%= link_to 'Back', user_gifts_path %>

app/views/users/_table.html.erb
<div class="center hero-unit">
  <table class="table" style="margin-top: 10%;">
    <tbody>
    <th>Image</th>
    <th><%= sort_link(@q, :email, 'Email', default_order: :desc) %></th>
    <th><%= sort_link(@q, :created_at, 'Date', default_order: :desc) %></th>
    <th>Is Admin</th>
    <th>Status</th>
    <% if user_signed_in? && current_user.role? %>
        <th>Choose image</th>
        <th>Delete</th>
        <th>Bann</th>
    <% end %>
    <% @users_list.each do |element| %>
        <tr>
          <td>
            <a href=<%= element.avatar.url%> class="fancybox">
                <%= image_tag element.avatar.url :thumb %>
            </a>
          </td>
          <td><%= element[:email] %></td>
          <td><%= element[:created_at] %></td>
          <td><%= element[:role] %></td>
          <td><%= element[:status] %></td>
          <% if user_signed_in? && current_user.role? %>
              <td><%= link_to 'Delete',  delete_user_path(element[:id]) %></td>

              <td>
                <%= form_for element, :url => avatar_user_path(element[:id]), :html => { :multipart => true } do |form| %>
                    <%= form.file_field :avatar %>

                    <%= form.submit %>
                <% end %>
              </td>
              <td><%= link_to 'Bann',  bann_user_path(element[:id]) %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @users_list %>
</div>

app/views/users/delete.html.erb
<h1>All users list</h1>

<%= render 'table' %>

app/views/users/index.html.erb
<h1>All users list</h1>

<%= render 'table' %>

app/views/users/new.html.erb
<h1>Register</h1>

<div class="center hero-unit">
  <%= form_for(@user) do |f| %>
      <p> Username:</br> <%= f.text_field :email %> </p>
      <%= f.submit :Signup %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>All users list</h1>

<div class="center hero-unit">
  <table class="table" style="margin-top: 10%;">
    <tbody>
    <th>Name</th>
    <th>Is Admin</th>
    <th>Date</th>
    <tr>
      <td><%= @user[:name] %></td>
      <td><%= @user[:role] %></td>
      <td><%= @user[:created_at] %></td>
    </tr>
    </tbody>
  </table>
</div>